export const iconMap = {
  users: '👥',
  award: '🏅',
  shield: '🛡️',
  star: '☆',
  calendar: '📅',
  phone: '📞',
  equipment: '▣',
  sterile: '◎',
  comfort: '♡',
  heart: '♡',
  check: '✓',
  implant: '♙',
  tooth: '🦷',
  'tooth-sparkle': '✧',
  xray: '▧',
  aligners: '⌘',
  extraction: '🦷',
  consultation: '▱',
  plan: '▣',
  treatment: '◈',
};
